version: '3.8'
services:
  thingsboard:
    image: thingsboard/tb-postgres:3.3.1
    container_name: thingsboard
    ports:
      - "8080:8080"
      - "1883:1883" # MQTT
      - "5683:5683/udp" # CoAP
    environment:
      TB_DATABASE_TS_TYPE: timescale
      TB_INSTALL_UPGRADE: "true"
      TB_QUEUE_TYPE: kafka
      TB_KAFKA_BROKERS: kafka:9092
    volumes:
      - ~/.thingsboard-data:/data
      - ~/.thingsboard-logs:/var/log/thingsboard
    depends_on:
      - timescaledb
      - kafka
      - zookeeper
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      - zookeeper
    restart: always

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: evdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ~/.timescaledb-data:/var/lib/postgresql/data
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always